config/routes.rb
Rails.application.routes.draw do
  
  resources :contacts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :content, presence: true
    validates :content, length: { maximum: 140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params.require(:contact).permit(:name,:email,:content)) 
    if @contact.save
      redirect_to new_contacts_path, notice:"お問い合わせありがとうございます！"
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/index.html.erb
<h1>お問い合わせ画面</h1>
<%= link_to "ブログを新規作成する", new_contact_path %>

app/views/contacts/new.html.erb
<h1>新規お問い合わせ画面</h1>
<%= form_with(model: @contact, local: true ) do |form| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= @contact.errors.count %>件のエラーがあります。
      </h2>
      <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="contact_title">
    <%= form.label :Name %>
    <%= form.text_field :name %>
  </div>
  <div class="contact_title">
    <%= form.label :Email %>
    <%= form.text_field :email %>
  </div>
  <div class="contact_title">
    <%= form.label :Content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit "Create Content" %>
  <br>
  <%= notice %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>